const mongoose = require("mongoose");

const CategorySchema = new mongoose.Schema({
  categoryId: { 
    type: String, 
    unique: true,
    required: false  // Will be auto-generated by pre-save hook
  },
  categoryName: { 
    type: String, 
    required: true,
    trim: true
  },
  industryId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Industry',
    required: true,
    index: true
  },
  description: {
    type: String,
    trim: true
  },
  isActive: { 
    type: Boolean, 
    default: true 
  },
  createdAt: { 
    type: Date, 
    default: Date.now 
  },
  updatedAt: { 
    type: Date, 
    default: Date.now 
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Admin'
  }
});

// Compound index for uniqueness within industry
CategorySchema.index({ industryId: 1, categoryName: 1 }, { unique: true });

// Middleware to generate sequential categoryId before saving
CategorySchema.pre("save", async function (next) {
  if (!this.categoryId) {
    const lastRecord = await this.constructor.findOne({}, { categoryId: 1 }).sort({ categoryId: -1 });

    // Extract last numeric part and increment
    let newIdNumber = lastRecord ? parseInt(lastRecord.categoryId, 10) + 1 : 1;

    // Format it as 3-digit (001, 002, etc.)
    this.categoryId = newIdNumber.toString().padStart(3, "0");
  }
  
  // Update the updatedAt timestamp
  this.updatedAt = Date.now();
  next();
});

module.exports = mongoose.model("Category", CategorySchema);
