const mongoose = require("mongoose");

const IndustrySchema = new mongoose.Schema({
  industryId: { 
    type: String, 
    unique: true,
    required: false  // Will be auto-generated by pre-save hook
  },
  industryName: { 
    type: String, 
    required: true, 
    unique: true,
    trim: true
  },
  description: {
    type: String,
    trim: true
  },
  isActive: { 
    type: Boolean, 
    default: true 
  },
  createdAt: { 
    type: Date, 
    default: Date.now 
  },
  updatedAt: { 
    type: Date, 
    default: Date.now 
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Admin'
  }
});

// Middleware to generate sequential industryId before saving
IndustrySchema.pre("save", async function (next) {
  if (!this.industryId) {
    const lastRecord = await this.constructor.findOne({}, { industryId: 1 }).sort({ industryId: -1 });

    // Extract last numeric part and increment
    let newIdNumber = lastRecord ? parseInt(lastRecord.industryId, 10) + 1 : 1;

    // Format it as 3-digit (001, 002, etc.)
    this.industryId = newIdNumber.toString().padStart(3, "0");
  }
  
  // Update the updatedAt timestamp
  this.updatedAt = Date.now();
  next();
});

module.exports = mongoose.model("Industry", IndustrySchema);
