const mongoose = require("mongoose");

const SubCategorySchema = new mongoose.Schema({
  subCategoryId: { 
    type: String, 
    unique: true,
    required: false  // Will be auto-generated by pre-save hook
  },
  subCategoryName: { 
    type: String, 
    required: true,
    trim: true
  },
  categoryId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Category',
    required: true,
    index: true
  },
  industryId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Industry',
    required: true,
    index: true
  },
  isChefRole: {
    type: Boolean,
    default: false
  },
  cuisines: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Cuisine'
  }],
  description: {
    type: String,
    trim: true
  },
  isActive: { 
    type: Boolean, 
    default: true 
  },
  createdAt: { 
    type: Date, 
    default: Date.now 
  },
  updatedAt: { 
    type: Date, 
    default: Date.now 
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Admin'
  }
});

// Compound index for uniqueness within category
SubCategorySchema.index({ categoryId: 1, subCategoryName: 1 }, { unique: true });

// Middleware to generate sequential subCategoryId before saving
SubCategorySchema.pre("save", async function (next) {
  if (!this.subCategoryId) {
    const lastRecord = await this.constructor.findOne({}, { subCategoryId: 1 }).sort({ subCategoryId: -1 });

    // Extract last numeric part and increment
    let newIdNumber = lastRecord ? parseInt(lastRecord.subCategoryId, 10) + 1 : 1;

    // Format it as 3-digit (001, 002, etc.)
    this.subCategoryId = newIdNumber.toString().padStart(3, "0");
  }
  
  // Update the updatedAt timestamp
  this.updatedAt = Date.now();
  next();
});

module.exports = mongoose.model("SubCategory", SubCategorySchema);
